### ISSUE TITLE
Provide an epub format

### ISSUE THREAD

**Issue by pixeline** [infoactive/data-design#45]
It would be awesome if the book could be downloaded as an .epub file, alongside the PDF format. Not sure how much work that means, though.

**Comment by nychang** [comment]
Maybe I can help?  I took Code School's HTML/CSS path.  Aaaaaand that's about all I know.  But if you point me to where I can read up on what you need for the epub CSS, I'll try not to break anything.

**Comment by faulconbridge** [comment]
Please, take a crack at it! Seems to me like the easiest route might be to start with the PDF stylesheets and modifying those to correct for any epub-specific quirks.

**Comment by nychang** [comment]
Alrighty.  I'll putz around with it later this month and see if I get anywhere with it.  But if someone else wants to hop on this gravy train before I get a clue, feel free to take the reins.

**Comment by nychang** [comment]
[epub's up on the site yo!](https://infoactive.co/data-design)  mobi too but it's not as nice because it's just a converted epub.
